services:
  - type: static_site
    name: petunia
    runtime: static
    buildCommand: npm install && npx expo export --platform web
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /**
        destination: /index.html
